- project:
    check:
      jobs:
        - noop
        - matt-check
        - sandbox-check
        - tim-sandbox-test
    gate:
      jobs:
        - noop
        - matt-check
    post:
      jobs:
        - sandbox-post
